sonar.projectKey=Student-Task-Manager
sonar.projectName=Student Task Manager

sonar.sources=server.js,database.js,public
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

sonar.exclusions=node_modules/**,tasks.db